services:
  backend:
    container_name: "RapidPay-Backend"
    build:
      dockerfile: Dockerfile
    ports:
      - "7320:80"
    depends_on:
      - database

  database:
    container_name: "RapidPay-Database"
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
